In [74]:
import pandas as pd
import numpy as np

In [75]:
d1 = {'Social_media_followers':[1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 4100000, 1600000, 2000000, 1000000],
      'Sold_out': [1, 0, 0, 1, 0, 0, 0, 1, 0, 1]}

In [76]:
df1 = pd.DataFrame(d1)

In [77]:
df1

   Social_media_followers  Sold_out
0               1000000.0         1
1                     NaN         0
2               2000000.0         0
3               1310000.0         1
4               1700000.0         0
5                     NaN         0
6               4100000.0         0
7               1600000.0         1
8               2000000.0         0
9               1000000.0         1

In [78]:
X1 = df1[['Social_media_followers']]

In [79]:
X1

   Social_media_followers
0               1000000.0
1                     NaN
2               2000000.0
3               1310000.0
4               1700000.0
5                     NaN
6               4100000.0
7               1600000.0
8               2000000.0
9               1000000.0

In [80]:
y1 = df1[['Sold_out']]

In [81]:
y1

   Sold_out
0         1
1         0
2         0
3         1
4         0
5         0
6         0
7         1
8         0
9         1

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=42)

In [84]:
X1_train.shape

(7, 1)

In [85]:
X1_test.shape

(3, 1)

In [86]:
from sklearn.impute import SimpleImputer

In [87]:
imputer = SimpleImputer(strategy='mean')

In [88]:
from sklearn.linear_model import LogisticRegression

In [89]:
lr = LogisticRegression()

In [90]:
from sklearn.pipeline import make_pipeline

In [91]:
pipe1 = make_pipeline(imputer, lr)

In [92]:
pipe1.fit(X1_train, y1_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('logisticregression', LogisticRegression())])

In [93]:
pipe1.score(X1_train, y1_train)

0.42857142857142855

In [94]:
pipe1.score(X1_test, y1_test)

1.0

In [95]:
pipe1.named_steps.simpleimputer.statistics_

array([1815714.28571429])

In [96]:
pipe1.named_steps.logisticregression.coef_

array([[-1.99443074e-07]])

In [97]:
d2 = {'Genre':['Rock', 'Metal', 'Bluegrass', 'Rock', np.nan, 'Rock', 'Rock', np.nan, 'Bluegrass', 'Rock'],
    'Social_media_followers':[1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 4100000, 1600000, 2200000, 1000000],
    'Sold_out':[1,0,0,1,0,0,0,1,0,1]}

In [98]:
df = pd.DataFrame(d2)
df.head()

       Genre  Social_media_followers  Sold_out
0       Rock               1000000.0         1
1      Metal                     NaN         0
2  Bluegrass               2000000.0         0
3       Rock               1310000.0         1
4        NaN               1700000.0         0

In [99]:
X = df.iloc[:, 0:2]

In [100]:
y = df.iloc[:, 2]

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=70)

In [102]:
num_cols = ['Social_media_followers']

In [103]:
cat_cols = ['Genre']

In [104]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [105]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

In [106]:
from sklearn.preprocessing import OneHotEncoder

In [107]:
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('one-hot-encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

In [108]:
from sklearn.compose import ColumnTransformer

In [109]:
col_transformer = ColumnTransformer(transformers = [
    ('num_pipeline', num_pipeline, num_cols),
    ('cat_pipeline', cat_pipeline, cat_cols)
],
                                    remainder = 'drop',
                                    n_jobs=-1)

In [110]:
from sklearn.tree import DecisionTreeClassifier

In [111]:
dtc = DecisionTreeClassifier()

In [112]:
pipefinal = make_pipeline(col_transformer, dtc)
pipefinal.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('num_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Social_media_followers']),
                                                 ('cat_pipeline',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot-encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Genre'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [113]:
pipefinal.score(X_test, y_test)

1.0

In [114]:
import joblib

In [115]:
joblib.dump(pipefinal, 'pipe.joblib')

['pipe.joblib']

In [116]:
pipefinal2 = joblib.load('pipe.joblib')

Building a Machine Learning Pipeline with Python and Scikit-Learn | Step-by-Step Tutorial: https://www.youtube.com/watch?v=T9ETsSD1I0w

SimpleImputer: https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html

Pipeline: https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline

make_pipeline: https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.make_pipeline.html

ColumnTransformer: https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html